### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by jfernandoghe** [GalAvineri/ISIC-Archive-Downloader#11]
Hello, I'm getting this error while trying to run

`python download_archive.py --num_images 1000`

Am a bit new to dataset download and loading, so... sorry if this is to basic... :/

```
File "download_archive.py", line 86
    def download_descriptions(ids: list, descs_dir: str, num_processes: int) -> list:
                                 ^
SyntaxError: invalid syntax

```
pip and pip3 updated, already checked Request, Pillow and tqdm.

Any idea? or I'm missing something...

Nice work tho! :) Pretty much what I was looking for!

**Comment by GalAvineri** [comment]
Hello there!
There's no such a thing as a bad question :)
If you're running into a problem, that means other (more shy) people have ran into it as well, and I thank you for bringing it up.

It seems to me that you are running the script with python 2, altough the project now requires to be ran with python 3 (it changed just a few days ago)

Can you kindly run the command `python --version` and tell me it's result? :)

**Comment by jfernandoghe** [comment]
I manage to run it on Python 3.*

`python --version` produces  Python2.*

The `python download_archive.py --num_images 1000` still doesn't work for me, all the remaining lines are good.

**Comment by GalAvineri** [comment]
I'm not sure what you mean by 
> I manage to run it on Python 3.*

If `python --version` outputs python 2 than `python download_archive.py --num_images 1000`
will also use python 2, which isn't how it should be used.

Instead of `python download_archive.py --num_images 1000`
can you tell me what the output of `python3 download_archive.py --num_images 1000` is?
