### ISSUE TITLE
README.md change "num_image" to "num-images"

### ISSUE THREAD

**Issue by shanecandoit** [GalAvineri/ISIC-Archive-Downloader#14]
Under "Optional download abilities":
- you give the command "python download_archive.py --num_images 1000"
- but the usage says this:
- "usage: download_archive.py [-h] [--num-images NUM_IMAGES]"

Fix the readme.md
- please change "python download_archive.py --num_images 1000"
- to "python download_archive.py --num-images 1000"

**Comment by GalAvineri** [comment]
You are absolutely right!
I've updated the Readme (3365ecd)
Thank you! :)
