### ISSUE TITLE
Choosing Datasets

### ISSUE THREAD

**Issue by karmdesai** [GalAvineri/ISIC-Archive-Downloader#27]
Hey, do you think it's possible for you to implement a feature where we can choose what dataset we want to download from? There are many datasets within the ISIC Archive, but I just want the HAM10000. Do you think that's possible?

Thanks for your help!

**Comment by GalAvineri** [comment]
Hey! :)
It would be possible to implement this feature :)
Though it would take me quite a while before i'll be able to spend time to implement it.
But in the mean while there are other sources from which you can download the HAM10000 dataset.
I've found the following:
1. [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtmlpersistentId=doi:10.7910/DVN/DBW86T)
2. [Kaggle](https://www.kaggle.com/kmader/skin-cancer-mnist-ham10000)

I hope that satisfies your need! :)
