### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by supriya2410** [GalAvineri/ISIC-Archive-Downloader#29]
Thank you for creating the script.

I tried running the script with all initial requirements installed. But getting below error:-
 
C:\Users\Supriya Singh\Documents\3rdSEM\ISIC-Archive-Downloader-master>python download_archive.py --filter benign
Traceback (most recent call last):
  File "download_archive.py", line 1, in <module>
    from download_single_item import LesionImageDownloader as ImgDownloader, SegmentationDownloader as SegDownloader
  File "C:\Users\Supriya Singh\Documents\3rdSEM\ISIC-Archive-Downloader-master\download_single_item.py", line 8, in <module>
    from PIL import Image
  File "C:\Users\Supriya Singh\Anaconda3\lib\site-packages\PIL\Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

C:\Users\Supriya Singh\Documents\3rdSEM\ISIC-Archive-Downloader-master>

Could you please help to find the cause?

**Comment by GalAvineri** [comment]
Hello! :)
It seems like the problem is not related to this repository but to pillow
and windows.
Could you try the suggestions on [this](
https://stackoverflow.com/questions/43264773/pil-dll-load-failed-specified-procedure-could-not-be-found)
stackoverflow page and let me know if you could solve your issue?

**Comment by supriya2410** [comment]
Hello,

Thanks a lot for the script :). Yes there was a problem with DLLs. I had to add the DLL path as well  to environment variable. It worked like a charm.

**Comment by GalAvineri** [comment]
I'm happy it works for you now! :)
If you encounter any other issues, feel free to open another issue :)
