### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by amralfy1** [GalAvineri/ISIC-Archive-Downloader#33]
when i run  "download_archive.py" it gives me this error:

 File "download_archive.py", line 1, in <module>
    from download_single_item import LesionImageDownloader as ImgDownloader, SegmentationDownloader as SegDownloader
  File "download_single_item.py", line 97
    img : Image.Image = Image.open(image_path)
        ^
SyntaxError: invalid syntax

**Comment by GalAvineri** [comment]
Can you check what version of python you are using?

**Comment by amralfy1** [comment]
I installed a newer python version and it ran perfectly thanx

**Comment by GalAvineri** [comment]
I'm glad to hear it :)
