### ISSUE TITLE
No option to set offset from where images should be download

### ISSUE THREAD

**Issue by mohitsvnit** [GalAvineri/ISIC-Archive-Downloader#6]
Let's say I already downloaded 1000 images and now I want to download 3000. 
But I have to download 1000 images again which I already downloaded. Instead, there should be one more parameter in `python download_dataset 3000` that tells offset from which number it should download images.

**Comment by GalAvineri** [comment]
Thats a wonderful idea, thank you :)
I'll work on it soon and it will probably be ready in the next few days

**Comment by mohitsvnit** [comment]
If you don't mind, I would love to contribute.

**Comment by GalAvineri** [comment]
Of course! It would be most welcome

**Comment by GalAvineri** [comment]
I've noticed there hasn't been any update and i had a bit of free time so i implemented this :)
However i would still highly appreciate ideas for more features and contributions, 
so please feel free to do so! :)

**Comment by GalAvineri** [comment]
This commit satisfies the request for the offest:
b0600d0

**Comment by mohitsvnit** [comment]
Sure. My exams are near. That's why I am pretty busy nowadays. Apology for the inconvenience.

**Comment by GalAvineri** [comment]
No inconvenience at all, just the opposite.
Good luck in your exams!
