### ISSUE TITLE
Selective download

### ISSUE THREAD

**Issue by FedericoLavatori** [GalAvineri/ISIC-Archive-Downloader#8]
Is it possible to use the code you provided to perform a selective download like only benign or only malignant images?

**Comment by GalAvineri** [comment]
Currently it isn't possible.
I will add an option to do so in the next few days :)

**Comment by GalAvineri** [comment]
I've found a way to insert the ability without damaging the runtime of users that do now user filtering.
So in conclusion the ability to download either only benign or only malignant images had been added :)
(50728c2)
